name: eda
channels:
  - conda-forge
dependencies:
  - python=3.5
  - appdirs  # jupyter/spyder requirement that won't auto-install
  - jupyter=1.0.0
  - jupyter_contrib_nbextensions=0.2.6
  - lmfit=0.9.6
  - matplotlib=2.0.0
#  - numexpr=2.6.1
  - numpy>=1.11.0
  - packaging  # jupyter/spyder requirement that won't auto-install
  - pandas>=0.20.0  # 20.0 for squeeze...
  - pyqt=4.11
  - scipy=0.19.0
  - spyder=3.1.4
  - sympy=1.0
  - pip
  - pip:
      - jupyterthemes

